services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=financial_data'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3305:3306'
    volumes:
      - ./db-scripts/nifi-user.sql:/docker-entrypoint-initdb.d/nifi-user.sql:ro